# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.java.home=C:\\Program Files\\Java\\jdk-21.0.10


minecraft_version=1.21.4
yarn_mappings=1.21.4+build.8
loader_version=0.16.14
loom_version=1.10-SNAPSHOT

# Mod Properties
mod_version=1.0.0+mc1.21.4
maven_group=ru.levin
archives_base_name=lovmod-fabric

# Dependencies
fabric_version=0.119.3+1.21.4