import java.util.ArrayList;
import java.util.List;
import shader.ShaderResource;

public class uz {
   private final List<ShaderResource> resources = new ArrayList<ShaderResource>();

   public uz() {
      this.a("hand_solid", this.d(), this.e());
      this.a("hand_balatro", this.f(), this.g());
      this.a("hand_glass", this.h(), this.i());
      this.a("hand_liquidglass", this.j(), this.k());
      this.a("hand_blend", this.l(), this.m());
   }

   private void a(String s, String s1, String s2) {
      String s3 = "shaders/core/" + s;
      this.resources.add(ShaderResource.b(s3 + ".json", s1.getBytes()));
      this.resources.add(ShaderResource.b(s3 + ".fsh", s2.getBytes()));
      this.resources.add(ShaderResource.b(s3 + ".vsh", this.c().getBytes()));
   }

   public List<ShaderResource> b() {
      return this.resources;
   }

   private String c() {
      return "#version 150\n\nin vec3 Position;\nin vec4 Color;\n\nuniform mat4 ModelViewMat;\nuniform mat4 ProjMat;\n\nout vec2 TexCoord;\nout vec4 FragColor;\n\nvoid main() {\n    gl_Position = ProjMat * ModelViewMat * vec4(Position, 1.0);\n    TexCoord = gl_Position.xy * 0.5 + 0.5;\n    FragColor = Color;\n}\n";
   }

   private String d() {
      return "{\n    \"vertex\": \"minecraft:core/hand_solid\",\n    \"fragment\": \"minecraft:core/hand_solid\",\n    \"samplers\": [\n        { \"name\": \"Sampler0\" },\n        { \"name\": \"Sampler1\" }\n    ],\n    \"uniforms\": [\n        { \"name\": \"ModelViewMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"ProjMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"Time\", \"type\": \"float\", \"count\": 1, \"values\": [ 0.0 ] },\n        { \"name\": \"Resolution\", \"type\": \"float\", \"count\": 2, \"values\": [ 1920.0, 1080.0 ] },\n        { \"name\": \"Color1\", \"type\": \"float\", \"count\": 3, \"values\": [ 1.0, 0.5, 0.3 ] },\n        { \"name\": \"Color2\", \"type\": \"float\", \"count\": 3, \"values\": [ 0.3, 0.5, 1.0 ] },\n        { \"name\": \"EffectAlpha\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.0 ] }\n    ]\n}\n";
   }

   private String e() {
      return "#version 150\n\nuniform sampler2D Sampler0;\nuniform sampler2D Sampler1;\nuniform float Time;\nuniform vec2 Resolution;\nuniform vec3 Color1;\nuniform vec3 Color2;\nuniform float EffectAlpha;\n\nin vec2 TexCoord;\nout vec4 OutColor;\n\nfloat dither(vec2 coord) {\n    return (fract(sin(dot(coord, vec2(12.9898, 78.233))) * 43758.5453) - 0.5) / 255.0;\n}\n\nvoid main() {\n    vec2 uv = gl_FragCoord.xy / Resolution;\n    vec4 color = texture(Sampler0, uv);\n    float depth = texture(Sampler1, uv).r;\n\n    if (depth < 0.9999) {\n        float gradient = sin(Time + uv.x * 3.14159 + uv.y * 2.0) * 0.5 + 0.5;\n        vec3 solidColor = mix(Color1, Color2, gradient);\n        solidColor += dither(gl_FragCoord.xy);\n        color.rgb = mix(color.rgb, solidColor, EffectAlpha);\n    }\n\n    OutColor = vec4(color.rgb, 1.0);\n}\n";
   }

   private String f() {
      return "{\n    \"vertex\": \"minecraft:core/hand_balatro\",\n    \"fragment\": \"minecraft:core/hand_balatro\",\n    \"samplers\": [\n        { \"name\": \"Sampler0\" },\n        { \"name\": \"Sampler1\" }\n    ],\n    \"uniforms\": [\n        { \"name\": \"ModelViewMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"ProjMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"Time\", \"type\": \"float\", \"count\": 1, \"values\": [ 0.0 ] },\n        { \"name\": \"Resolution\", \"type\": \"float\", \"count\": 2, \"values\": [ 1920.0, 1080.0 ] },\n        { \"name\": \"BColor1\", \"type\": \"float\", \"count\": 3, \"values\": [ 0.87, 0.24, 0.19 ] },\n        { \"name\": \"BColor2\", \"type\": \"float\", \"count\": 3, \"values\": [ 0.0, 0.42, 0.87 ] },\n        { \"name\": \"BColor3\", \"type\": \"float\", \"count\": 3, \"values\": [ 0.15, 0.52, 0.33 ] },\n        { \"name\": \"BColor4\", \"type\": \"float\", \"count\": 3, \"values\": [ 0.59, 0.27, 0.0 ] }\n    ]\n}\n";
   }

   private String g() {
      return "#version 150\n\nuniform sampler2D Sampler0;\nuniform sampler2D Sampler1;\nuniform float Time;\nuniform vec2 Resolution;\nuniform vec3 BColor1;\nuniform vec3 BColor2;\nuniform vec3 BColor3;\nuniform vec3 BColor4;\n\nin vec2 TexCoord;\nout vec4 OutColor;\n\nfloat hash(vec2 p) {\n    return fract(sin(dot(p, vec2(127.1, 311.7))) * 43758.5453);\n}\n\nfloat noise(vec2 p) {\n    vec2 i = floor(p);\n    vec2 f = fract(p);\n    f = f * f * (3.0 - 2.0 * f);\n    float a = hash(i);\n    float b = hash(i + vec2(1.0, 0.0));\n    float c = hash(i + vec2(0.0, 1.0));\n    float d = hash(i + vec2(1.0, 1.0));\n    return mix(mix(a, b, f.x), mix(c, d, f.x), f.y);\n}\n\nfloat fbm(vec2 p) {\n    float v = 0.0;\n    float a = 0.5;\n    vec2 shift = vec2(100.0);\n    for (int i = 0; i < 5; i++) {\n        v += a * noise(p);\n        p = p * 2.0 + shift;\n        a *= 0.5;\n    }\n    return v;\n}\n\nvoid main() {\n    vec4 color = texture(Sampler0, TexCoord);\n    float depth = texture(Sampler1, TexCoord).r;\n\n    if (depth < 0.9999) {\n        vec2 uv = TexCoord * Resolution / min(Resolution.x, Resolution.y);\n        float t = Time * 0.5;\n\n        float n1 = fbm(uv * 2.0 + vec2(t * 0.3, t * 0.2));\n        float n2 = fbm(uv * 3.0 + vec2(t * -0.2, t * 0.4) + n1 * 2.0);\n        float n3 = fbm(uv * 1.5 + vec2(t * 0.1, t * -0.3) + n2 * 1.5);\n\n        vec3 c = BColor1;\n        c = mix(c, BColor2, smoothstep(0.2, 0.5, n1));\n        c = mix(c, BColor3, smoothstep(0.3, 0.6, n2));\n        c = mix(c, BColor4, smoothstep(0.4, 0.7, n3));\n\n        color.rgb = c;\n    }\n\n    OutColor = color;\n}\n";
   }

   private String h() {
      return "{\n    \"vertex\": \"minecraft:core/hand_glass\",\n    \"fragment\": \"minecraft:core/hand_glass\",\n    \"samplers\": [\n        { \"name\": \"Sampler0\" },\n        { \"name\": \"Sampler1\" },\n        { \"name\": \"Sampler2\" }\n    ],\n    \"uniforms\": [\n        { \"name\": \"ModelViewMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"ProjMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"Time\", \"type\": \"float\", \"count\": 1, \"values\": [ 0.0 ] },\n        { \"name\": \"Resolution\", \"type\": \"float\", \"count\": 2, \"values\": [ 1920.0, 1080.0 ] },\n        { \"name\": \"BlurSize\", \"type\": \"float\", \"count\": 1, \"values\": [ 50.0 ] },\n        { \"name\": \"Quality\", \"type\": \"float\", \"count\": 1, \"values\": [ 10.0 ] },\n        { \"name\": \"Direction\", \"type\": \"float\", \"count\": 1, \"values\": [ 10.0 ] },\n        { \"name\": \"Refraction\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.0 ] },\n        { \"name\": \"GlassBrightness\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.1 ] },\n        { \"name\": \"EnableChromatic\", \"type\": \"int\", \"count\": 1, \"values\": [ 1 ] },\n        { \"name\": \"EnableDistortion\", \"type\": \"int\", \"count\": 1, \"values\": [ 0 ] },\n        { \"name\": \"HideHand\", \"type\": \"int\", \"count\": 1, \"values\": [ 1 ] },\n        { \"name\": \"BackgroundBlur\", \"type\": \"float\", \"count\": 1, \"values\": [ 70.0 ] }\n    ]\n}\n";
   }

   private String i() {
      return "#version 150\n\nuniform sampler2D Sampler0;\nuniform sampler2D Sampler1;\nuniform sampler2D Sampler2;\nuniform float Time;\nuniform vec2 Resolution;\nuniform float BlurSize;\nuniform float Quality;\nuniform float Direction;\nuniform float Refraction;\nuniform float GlassBrightness;\nuniform int EnableChromatic;\nuniform int EnableDistortion;\nuniform int HideHand;\nuniform float BackgroundBlur;\n\nin vec2 TexCoord;\nout vec4 OutColor;\n\nconst float PI = 3.14159265359;\nconst float TAU = 6.28318530718;\n\nvec3 blur(sampler2D tex, vec2 uv, float radius, float quality, float directions) {\n    vec2 pixelSize = radius / Resolution;\n    vec3 col = texture(tex, uv).rgb;\n    float count = 1.0;\n\n    for (float d = 0.0; d < TAU; d += TAU / directions) {\n        for (float i = 1.0; i <= quality; i += 1.0) {\n            vec2 offset = vec2(cos(d), sin(d)) * pixelSize * (i / quality);\n            col += texture(tex, uv + offset).rgb;\n            count += 1.0;\n        }\n    }\n\n    return col / count;\n}\n\nvoid main() {\n    vec4 color = texture(Sampler0, TexCoord);\n    float depth = texture(Sampler1, TexCoord).r;\n    bool isHand = depth < 0.9999;\n\n    if (isHand) {\n        if (HideHand == 1) {\n            vec3 bg;\n            if (BackgroundBlur <= 0.001) {\n                bg = texture(Sampler2, TexCoord).rgb;\n            } else {\n                bg = blur(Sampler2, TexCoord, BackgroundBlur, Quality, Direction);\n            }\n            color.rgb = bg * GlassBrightness;\n        } else {\n            vec2 distortedUV = TexCoord;\n            if (EnableDistortion == 1) {\n                distortedUV += vec2(\n                    sin(TexCoord.y * 20.0 + Time * 2.0) * 0.003 * Refraction,\n                    cos(TexCoord.x * 20.0 + Time * 2.0) * 0.003 * Refraction\n                );\n            }\n\n            if (EnableChromatic == 1) {\n                float offset = Refraction * 0.002;\n                float r = blur(Sampler0, distortedUV + vec2(offset, 0.0), BlurSize, Quality, Direction).r;\n                float g = blur(Sampler0, distortedUV, BlurSize, Quality, Direction).g;\n                float b = blur(Sampler0, distortedUV - vec2(offset, 0.0), BlurSize, Quality, Direction).b;\n                color.rgb = vec3(r, g, b) * GlassBrightness;\n            } else {\n                color.rgb = blur(Sampler0, distortedUV, BlurSize, Quality, Direction) * GlassBrightness;\n            }\n        }\n    }\n\n    OutColor = color;\n}\n";
   }

   private String j() {
      return "{\n    \"vertex\": \"minecraft:core/hand_liquidglass\",\n    \"fragment\": \"minecraft:core/hand_liquidglass\",\n    \"samplers\": [\n        { \"name\": \"Sampler0\" },\n        { \"name\": \"Sampler1\" },\n        { \"name\": \"Sampler2\" }\n    ],\n    \"uniforms\": [\n        { \"name\": \"ModelViewMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"ProjMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"Resolution\", \"type\": \"float\", \"count\": 2, \"values\": [ 1920.0, 1080.0 ] },\n        { \"name\": \"DistortStrength\", \"type\": \"float\", \"count\": 1, \"values\": [ 0.08 ] },\n        { \"name\": \"FresnelPower\", \"type\": \"float\", \"count\": 1, \"values\": [ 2.0 ] },\n        { \"name\": \"GlassBrightness\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.1 ] },\n        { \"name\": \"BackgroundBlur\", \"type\": \"float\", \"count\": 1, \"values\": [ 70.0 ] },\n        { \"name\": \"Quality\", \"type\": \"float\", \"count\": 1, \"values\": [ 10.0 ] },\n        { \"name\": \"Direction\", \"type\": \"float\", \"count\": 1, \"values\": [ 10.0 ] },\n        { \"name\": \"EdgeRadius\", \"type\": \"float\", \"count\": 1, \"values\": [ 4.0 ] },\n        { \"name\": \"EdgeDirections\", \"type\": \"float\", \"count\": 1, \"values\": [ 8.0 ] },\n        { \"name\": \"FresnelHighlight\", \"type\": \"float\", \"count\": 1, \"values\": [ 0.2 ] }\n    ]\n}\n";
   }

   private String k() {
      return "#version 150\n\nuniform sampler2D Sampler0;\nuniform sampler2D Sampler1;\nuniform sampler2D Sampler2;\nuniform vec2 Resolution;\nuniform float DistortStrength;\nuniform float FresnelPower;\nuniform float GlassBrightness;\nuniform float BackgroundBlur;\nuniform float Quality;\nuniform float Direction;\nuniform float EdgeRadius;\nuniform float EdgeDirections;\nuniform float FresnelHighlight;\n\nin vec2 TexCoord;\nout vec4 OutColor;\n\nconst float TAU = 6.28318530718;\n\nvec3 blur(sampler2D tex, vec2 uv, float radius, float quality, float directions) {\n    vec2 pixelSize = radius / Resolution;\n    vec3 col = texture(tex, uv).rgb;\n    float count = 1.0;\n    for (float d = 0.0; d < TAU; d += TAU / directions) {\n        for (float i = 1.0; i <= quality; i += 1.0) {\n            vec2 offset = vec2(cos(d), sin(d)) * pixelSize * (i / quality);\n            col += texture(tex, uv + offset).rgb;\n            count += 1.0;\n        }\n    }\n    return col / count;\n}\n\nvoid main() {\n    vec4 color = texture(Sampler0, TexCoord);\n    float depth = texture(Sampler1, TexCoord).r;\n\n    if (depth >= 0.9999) {\n        OutColor = vec4(color.rgb, 1.0);\n        return;\n    }\n\n    // Edge proximity via depth sampling\n    vec2 texel = 1.0 / Resolution;\n    float edgeFactor = 0.0;\n\n    for (float a = 0.0; a < TAU; a += TAU / EdgeDirections) {\n        vec2 dir = vec2(cos(a), sin(a));\n        for (float r = 1.0; r <= EdgeRadius; r += 1.0) {\n            if (texture(Sampler1, TexCoord + dir * texel * r * 2.0).r >= 0.9999) {\n                edgeFactor += 1.0 - (r - 1.0) / EdgeRadius;\n                break;\n            }\n        }\n    }\n    edgeFactor /= EdgeDirections;\n\n    // Fresnel from edge proximity\n    float fresnel;\n    if (FresnelPower > 20.0) {\n        fresnel = exp(FresnelPower * log(clamp(edgeFactor, 0.001, 1.0)));\n    } else {\n        fresnel = pow(clamp(edgeFactor, 0.001, 1.0), max(FresnelPower, 0.1));\n    }\n    fresnel = clamp(fresnel, 0.0, 1.0);\n\n    // Direction-based UV distortion (from screen center)\n    vec2 screenCenter = vec2(0.5);\n    vec2 distDir = normalize(TexCoord - screenCenter);\n    vec2 distortedUV = TexCoord + distDir * fresnel * DistortStrength;\n\n    // Sample background with distortion + blur\n    vec3 bg;\n    if (BackgroundBlur <= 0.001) {\n        bg = texture(Sampler2, distortedUV).rgb;\n    } else {\n        bg = blur(Sampler2, distortedUV, BackgroundBlur, Quality, Direction);\n    }\n\n    // Glass: distorted background + fresnel edge highlight\n    color.rgb = bg * GlassBrightness + vec3(1.0) * fresnel * FresnelHighlight;\n\n    OutColor = vec4(color.rgb, 1.0);\n}\n";
   }

   private String l() {
      return "{\n    \"vertex\": \"minecraft:core/hand_blend\",\n    \"fragment\": \"minecraft:core/hand_blend\",\n    \"samplers\": [\n        { \"name\": \"Sampler0\" },\n        { \"name\": \"Sampler1\" },\n        { \"name\": \"Sampler2\" }\n    ],\n    \"uniforms\": [\n        { \"name\": \"ModelViewMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"ProjMat\", \"type\": \"matrix4x4\", \"count\": 16, \"values\": [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0 ] },\n        { \"name\": \"BlendMode\", \"type\": \"int\", \"count\": 1, \"values\": [ 0 ] },\n        { \"name\": \"BlendIntensity\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.0 ] },\n        { \"name\": \"Shader1Strength\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.0 ] },\n        { \"name\": \"Shader2Strength\", \"type\": \"float\", \"count\": 1, \"values\": [ 1.0 ] }\n    ]\n}\n";
   }

   private String m() {
      return "#version 150\n\nuniform sampler2D Sampler0;\nuniform sampler2D Sampler1;\nuniform sampler2D Sampler2;\nuniform int BlendMode;\nuniform float BlendIntensity;\nuniform float Shader1Strength;\nuniform float Shader2Strength;\n\nin vec2 TexCoord;\nout vec4 OutColor;\n\nvoid main() {\n    vec4 s1 = texture(Sampler0, TexCoord);\n    vec4 s2 = texture(Sampler1, TexCoord);\n    float depth = texture(Sampler2, TexCoord).r;\n\n    if (depth >= 0.9999) {\n        OutColor = vec4(s1.rgb, 1.0);\n        return;\n    }\n\n    vec3 c1 = s1.rgb * Shader1Strength;\n    vec3 c2 = s2.rgb * Shader2Strength;\n    vec3 result;\n\n    if (BlendMode == 0) {\n        result = mix(c1, c2, 0.5);\n    } else if (BlendMode == 1) {\n        result = c1 + c2;\n    } else if (BlendMode == 2) {\n        result = c1 * c2;\n    } else {\n        result = abs(c1 - c2);\n    }\n\n    result = mix(s1.rgb, result, BlendIntensity);\n    OutColor = vec4(clamp(result, 0.0, 1.0), 1.0);\n}\n";
   }
}
